from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from _schema import INDEX_HEADERS, OS_DIR
from _paths import indexes_dir, project_os, project_relative_or_absolute
from _project_io import read_tsv


DATA_ASSETS_GENERATED_SIGNATURE = 'Human-facing data/source view generated from `.project_os/indexes/assets.tsv`.'
DATA_ASSETS_GENERATED_EXPORT = 'DATA_ASSETS.generated.md'


def is_generated_data_assets_markdown_text(text: str) -> bool:
    normalized = text.replace('\r\n', '\n').lstrip('\ufeff')
    return normalized.startswith(f'# DATA_ASSETS\n\n{DATA_ASSETS_GENERATED_SIGNATURE}')


def is_generated_data_assets_markdown(path: Path) -> bool:
    if not path.exists():
        return False
    return is_generated_data_assets_markdown_text(path.read_text(encoding='utf-8', errors='replace'))


def data_assets_generated_export_path(root: Path) -> Path:
    return project_os(root) / 'exports' / 'views' / DATA_ASSETS_GENERATED_EXPORT


def data_assets_markdown_text(root: Path) -> str:
    rows = read_tsv(indexes_dir(root) / 'assets.tsv')
    location_rows = read_tsv(indexes_dir(root) / 'asset_locations.tsv') if (indexes_dir(root) / 'asset_locations.tsv').exists() else []
    usage_rows = read_tsv(indexes_dir(root) / 'asset_usage.tsv') if (indexes_dir(root) / 'asset_usage.tsv').exists() else []
    usage_count: dict[str, int] = {}
    location_count: dict[str, int] = {}
    primary_paths: dict[str, str] = {}
    for item in usage_rows:
        aid = item.get('asset_id', '')
        usage_count[aid] = usage_count.get(aid, 0) + 1
    for item in location_rows:
        aid = item.get('asset_id', '')
        location_count[aid] = location_count.get(aid, 0) + 1
        if item.get('role') == 'primary' and item.get('path'):
            primary_paths[aid] = item.get('path', '')
    lines = ['# DATA_ASSETS', '', DATA_ASSETS_GENERATED_SIGNATURE, '']
    if not rows:
        lines += ['No registered assets yet.', '', '## Policy', '', '- Canonical rows live in `.project_os/indexes/assets.tsv`.', '- Multi-location rows live in `.project_os/indexes/asset_locations.tsv`.', '- Usage links live in `.project_os/indexes/asset_usage.tsv`.', '- Do not infer provenance from filenames alone.', '']
        return '\n'.join(lines).rstrip() + '\n'
    lines += ['| asset_id | kind | status | immutable | version | primary path/source | checksum | locations | usage_count | notes |', '|---|---|---|---:|---|---|---|---:|---:|---|']
    for row in rows:
        aid = row.get('asset_id', '')
        path_or_source = primary_paths.get(aid) or row.get('path') or row.get('source_url', '')
        lines.append(f"| `{aid}` | {row.get('kind','')} | {row.get('status','')} | {row.get('immutable','')} | {row.get('version','')} | `{path_or_source}` | `{row.get('checksum','')}` | {location_count.get(aid, 0)} | {usage_count.get(aid, 0)} | {row.get('notes','')} |")
    lines += ['', '## Policy', '', '- Canonical rows live in `.project_os/indexes/assets.tsv`.', '- Multi-location rows live in `.project_os/indexes/asset_locations.tsv`.', '- Usage links live in `.project_os/indexes/asset_usage.tsv`.', '- Do not infer provenance from filenames alone.', '']
    return '\n'.join(lines).rstrip() + '\n'


def data_assets_view_status(root: Path) -> dict[str, Any]:
    expected = data_assets_markdown_text(root)
    root_doc = root / 'DATA_ASSETS.md'
    export_doc = data_assets_generated_export_path(root)
    if not root_doc.exists() or is_generated_data_assets_markdown(root_doc):
        existing = root_doc.read_text(encoding='utf-8', errors='replace').replace('\r\n', '\n') if root_doc.exists() else ''
        return {
            'mode': 'managed_root',
            'path': 'DATA_ASSETS.md',
            'root_path': 'DATA_ASSETS.md',
            'generated_export_path': f'{OS_DIR}/exports/views/{DATA_ASSETS_GENERATED_EXPORT}',
            'root_protected': False,
            'exists': root_doc.exists(),
            'stale': root_doc.exists() and existing != expected,
        }
    existing_export = export_doc.read_text(encoding='utf-8', errors='replace').replace('\r\n', '\n') if export_doc.exists() else ''
    return {
        'mode': 'protected_human_root',
        'path': f'{OS_DIR}/exports/views/{DATA_ASSETS_GENERATED_EXPORT}',
        'root_path': 'DATA_ASSETS.md',
        'generated_export_path': f'{OS_DIR}/exports/views/{DATA_ASSETS_GENERATED_EXPORT}',
        'root_protected': True,
        'exists': export_doc.exists(),
        'stale': (not export_doc.exists()) or existing_export != expected,
    }


def refresh_data_assets_markdown(root: Path) -> dict[str, Any]:
    """Refresh the generated DATA_ASSETS view without overwriting human docs.

    Existing projects may already have a hand-authored root DATA_ASSETS.md. The
    root file is refreshed only when it is absent or clearly generated by this
    harness. Otherwise the generated view is written under
    .project_os/exports/views/ so adoption/externalization cannot destroy a
    project-specific registry or handoff document.
    """
    text = data_assets_markdown_text(root)
    root_doc = root / 'DATA_ASSETS.md'
    export_doc = data_assets_generated_export_path(root)
    if not root_doc.exists() or is_generated_data_assets_markdown(root_doc):
        root_doc.write_text(text, encoding='utf-8')
        return {
            'path': 'DATA_ASSETS.md',
            'mode': 'managed_root',
            'written': True,
            'root_protected': False,
            'skipped_root_reason': '',
        }

    export_doc.parent.mkdir(parents=True, exist_ok=True)
    export_doc.write_text(text, encoding='utf-8')
    return {
        'path': f'{OS_DIR}/exports/views/{DATA_ASSETS_GENERATED_EXPORT}',
        'mode': 'protected_human_root',
        'written': True,
        'root_protected': True,
        'skipped_root_reason': 'Existing root DATA_ASSETS.md is not a harness-generated view; preserved and wrote generated view under .project_os/exports/views/.',
    }


def current_targets(row: dict[str, str]) -> list[str]:
    return [item.strip() for item in row.get('promoted_to', '').split(',') if item.strip()]


def target_scope(target: str) -> dict[str, str]:
    if target.startswith('current/project/'):
        return {'scope': 'project', 'branch_id': '', 'target': target}
    match = re.match(r'^current/branches/([^/]+)/', target)
    if match:
        return {'scope': 'branch', 'branch_id': match.group(1), 'target': target}
    if target.startswith('current/'):
        return {'scope': 'current_other', 'branch_id': '', 'target': target}
    return {'scope': 'non_current', 'branch_id': '', 'target': target}


def enrich_current_row(row: dict[str, str]) -> dict[str, Any]:
    targets = current_targets(row)
    scopes = [target_scope(target) for target in targets]
    return {
        **row,
        'current_targets': targets,
        'current_scopes': scopes,
        'is_current_status': row.get('status') == 'current',
    }


def current_result_views(root: Path, rows: list[dict[str, str]] | None = None) -> dict[str, Any]:
    rows = rows if rows is not None else read_tsv(indexes_dir(root) / 'results.tsv')
    current_rows = [row for row in rows if row.get('status') == 'current' or current_targets(row)]
    enriched = [enrich_current_row(row) for row in current_rows]
    project_results = [row for row in enriched if any(scope.get('scope') == 'project' for scope in row.get('current_scopes', []))]
    branches: dict[str, dict[str, Any]] = {}
    for row in enriched:
        branch_ids = {scope.get('branch_id', '') for scope in row.get('current_scopes', []) if scope.get('scope') == 'branch' and scope.get('branch_id')}
        # Preserve branch-local visibility for legacy/migrated status=current
        # rows only when they have no explicit promoted target at all. Project
        # current targets should not automatically appear in branch-current
        # views unless they also have a current/branches/<branch_id>/ target.
        if row.get('status') == 'current' and row.get('branch_id') and not row.get('current_targets'):
            branch_ids.add(str(row.get('branch_id')))
        for branch_id in sorted(branch_ids):
            bucket = branches.setdefault(branch_id, {'count': 0, 'results': []})
            bucket['results'].append(row)
    for bucket in branches.values():
        bucket['count'] = len(bucket['results'])
    return {
        'all': {'count': len(enriched), 'results': enriched},
        'project': {'count': len(project_results), 'results': project_results},
        'branches': dict(sorted(branches.items())),
    }


def promotion_audit(root: Path, rows: list[dict[str, str]] | None = None) -> dict[str, Any]:
    rows = rows if rows is not None else read_tsv(indexes_dir(root) / 'results.tsv')
    missing_targets: list[dict[str, str]] = []
    cross_branch_targets: list[dict[str, str]] = []
    unscoped_current: list[dict[str, str]] = []
    duplicate_targets: list[dict[str, Any]] = []
    seen_targets: dict[str, list[str]] = {}

    for row in rows:
        targets = current_targets(row)
        if row.get('status') == 'current' and not targets:
            unscoped_current.append({'result_id': row.get('result_id', ''), 'branch_id': row.get('branch_id', '')})
        for target in targets:
            target_path, _ = project_relative_or_absolute(root, target)
            if target.startswith('current/') and not target_path.exists():
                missing_targets.append({'result_id': row.get('result_id', ''), 'target': target})
            scope = target_scope(target)
            if scope.get('scope') == 'branch' and scope.get('branch_id') and row.get('branch_id') and scope['branch_id'] != row.get('branch_id'):
                cross_branch_targets.append({'result_id': row.get('result_id', ''), 'branch_id': row.get('branch_id', ''), 'target': target})
            seen_targets.setdefault(target, []).append(row.get('result_id', ''))

    for target, result_ids in sorted(seen_targets.items()):
        unique = sorted({rid for rid in result_ids if rid})
        if len(unique) > 1:
            duplicate_targets.append({'target': target, 'result_ids': unique})

    return {
        'missing_current_targets': missing_targets,
        'cross_branch_promotions': cross_branch_targets,
        'unscoped_current_results': unscoped_current,
        'duplicate_current_targets': duplicate_targets,
        'ok': not (missing_targets or cross_branch_targets or duplicate_targets),
    }


def results_index_markdown_text(root: Path) -> str:
    rows = read_tsv(indexes_dir(root) / 'results.tsv')
    lines = ['# RESULTS_INDEX', '', 'Human-facing index generated from `.project_os/indexes/results.tsv`.', '']
    current_views = current_result_views(root, rows)
    if current_views['project']['count'] or current_views['branches']:
        lines += ['## Current views', '']
        if current_views['project']['count']:
            lines += ['### Project current', '']
            for r in current_views['project']['results']:
                targets = ', '.join(f"`{target}`" for target in r.get('current_targets', []))
                lines.append(f"- `{r.get('result_id','')}` [{r.get('type','')}] source `{r.get('path','')}` -> {targets}")
            lines.append('')
        for branch_id, bucket in current_views['branches'].items():
            lines += [f'### Branch `{branch_id}` current', '']
            for r in bucket['results']:
                branch_targets = [scope['target'] for scope in r.get('current_scopes', []) if scope.get('scope') == 'branch' and scope.get('branch_id') == branch_id]
                targets = ', '.join(f"`{target}`" for target in branch_targets) or '(status=current without branch target)'
                lines.append(f"- `{r.get('result_id','')}` [{r.get('type','')}] source `{r.get('path','')}` -> {targets}")
            lines.append('')
    for status in ['current', 'accepted', 'candidate', 'draft', 'superseded', 'legacy', 'release']:
        subset = [r for r in rows if r.get('status') == status]
        if not subset:
            continue
        lines += [f'## {status}', '']
        for r in subset:
            lines.append(f"- `{r.get('result_id','')}` [{r.get('type','')}] `{r.get('path','')}` — branch `{r.get('branch_id','')}`, run `{r.get('run_id','')}`")
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def refresh_results_index_markdown(root: Path) -> None:
    (root / 'RESULTS_INDEX.md').write_text(results_index_markdown_text(root), encoding='utf-8')
